### ISSUE TITLE
Import from typescript file?

### ISSUE THREAD

**Issue by kobyl** [bencompton/framework7-react#51]
Hello,

  General question - perhaps something for the documentation if I'm not just doing something dumb. :)

I've written a bunch of code using es6 and now want to try typescript. This:
import {List} from 'framework7-react'

fails during ts compile with a 'cannot find module 'framework7-react'. It works if I switch out to .jsx

Is there another syntax I need to use here?

Thanks!

Koby

**Comment by bencompton** [comment]
That import syntax is correct. I would have to see your build pipeline and settings to be of much further help. For example, are you using Webpack, what does your tsconfig.json file look like, etc.?

There are currently no TypeScript starter templates, but the kitchen sink uses TypeScript as you might have seen, and it has its own package.json and can be built separately from framework7-react. If you pull out the kitchen sink directory, delete the file dependency to framework7-react in package.json and run `npm install framework7-react --save`, it could act as a starter template.

**Comment by kobyl** [comment]
Ah - thought it was something simple. Sorry - didn't see that kitchensink was typescript. I just needed to add "moduleResolution": "node" to my tsconfig.json and all was well.

Thanks!
